/*
Copyright (c) 2020 Mandelsoft. All rights reserved. This file is licensed under the Apache Software License, v. 2 except as noted otherwise in the LICENSE file

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

     http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// BootProfileListerExpansion allows custom methods to be added to
// BootProfileLister.
type BootProfileListerExpansion interface{}

// BootProfileNamespaceListerExpansion allows custom methods to be added to
// BootProfileNamespaceLister.
type BootProfileNamespaceListerExpansion interface{}

// BootProfileMatcherListerExpansion allows custom methods to be added to
// BootProfileMatcherLister.
type BootProfileMatcherListerExpansion interface{}

// BootProfileMatcherNamespaceListerExpansion allows custom methods to be added to
// BootProfileMatcherNamespaceLister.
type BootProfileMatcherNamespaceListerExpansion interface{}

// BootResourceListerExpansion allows custom methods to be added to
// BootResourceLister.
type BootResourceListerExpansion interface{}

// BootResourceNamespaceListerExpansion allows custom methods to be added to
// BootResourceNamespaceLister.
type BootResourceNamespaceListerExpansion interface{}

// MachineListerExpansion allows custom methods to be added to
// MachineLister.
type MachineListerExpansion interface{}

// MachineNamespaceListerExpansion allows custom methods to be added to
// MachineNamespaceLister.
type MachineNamespaceListerExpansion interface{}

// MetaDataMapperListerExpansion allows custom methods to be added to
// MetaDataMapperLister.
type MetaDataMapperListerExpansion interface{}

// MetaDataMapperNamespaceListerExpansion allows custom methods to be added to
// MetaDataMapperNamespaceLister.
type MetaDataMapperNamespaceListerExpansion interface{}
