/*
Copyright (c) 2020 Mandelsoft. All rights reserved. This file is licensed under the Apache Software License, v. 2 except as noted otherwise in the LICENSE file

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

     http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"time"

	v1alpha1 "github.com/mandelsoft/kipxe/pkg/apis/ipxe/v1alpha1"
	scheme "github.com/mandelsoft/kipxe/pkg/client/ipxe/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// BootProfileMatchersGetter has a method to return a BootProfileMatcherInterface.
// A group's client should implement this interface.
type BootProfileMatchersGetter interface {
	BootProfileMatchers(namespace string) BootProfileMatcherInterface
}

// BootProfileMatcherInterface has methods to work with BootProfileMatcher resources.
type BootProfileMatcherInterface interface {
	Create(*v1alpha1.BootProfileMatcher) (*v1alpha1.BootProfileMatcher, error)
	Update(*v1alpha1.BootProfileMatcher) (*v1alpha1.BootProfileMatcher, error)
	UpdateStatus(*v1alpha1.BootProfileMatcher) (*v1alpha1.BootProfileMatcher, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.BootProfileMatcher, error)
	List(opts v1.ListOptions) (*v1alpha1.BootProfileMatcherList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.BootProfileMatcher, err error)
	BootProfileMatcherExpansion
}

// bootProfileMatchers implements BootProfileMatcherInterface
type bootProfileMatchers struct {
	client rest.Interface
	ns     string
}

// newBootProfileMatchers returns a BootProfileMatchers
func newBootProfileMatchers(c *IpxeV1alpha1Client, namespace string) *bootProfileMatchers {
	return &bootProfileMatchers{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the bootProfileMatcher, and returns the corresponding bootProfileMatcher object, and an error if there is any.
func (c *bootProfileMatchers) Get(name string, options v1.GetOptions) (result *v1alpha1.BootProfileMatcher, err error) {
	result = &v1alpha1.BootProfileMatcher{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("bootprofilematchers").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of BootProfileMatchers that match those selectors.
func (c *bootProfileMatchers) List(opts v1.ListOptions) (result *v1alpha1.BootProfileMatcherList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.BootProfileMatcherList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("bootprofilematchers").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested bootProfileMatchers.
func (c *bootProfileMatchers) Watch(opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("bootprofilematchers").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a bootProfileMatcher and creates it.  Returns the server's representation of the bootProfileMatcher, and an error, if there is any.
func (c *bootProfileMatchers) Create(bootProfileMatcher *v1alpha1.BootProfileMatcher) (result *v1alpha1.BootProfileMatcher, err error) {
	result = &v1alpha1.BootProfileMatcher{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("bootprofilematchers").
		Body(bootProfileMatcher).
		Do().
		Into(result)
	return
}

// Update takes the representation of a bootProfileMatcher and updates it. Returns the server's representation of the bootProfileMatcher, and an error, if there is any.
func (c *bootProfileMatchers) Update(bootProfileMatcher *v1alpha1.BootProfileMatcher) (result *v1alpha1.BootProfileMatcher, err error) {
	result = &v1alpha1.BootProfileMatcher{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("bootprofilematchers").
		Name(bootProfileMatcher.Name).
		Body(bootProfileMatcher).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *bootProfileMatchers) UpdateStatus(bootProfileMatcher *v1alpha1.BootProfileMatcher) (result *v1alpha1.BootProfileMatcher, err error) {
	result = &v1alpha1.BootProfileMatcher{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("bootprofilematchers").
		Name(bootProfileMatcher.Name).
		SubResource("status").
		Body(bootProfileMatcher).
		Do().
		Into(result)
	return
}

// Delete takes name of the bootProfileMatcher and deletes it. Returns an error if one occurs.
func (c *bootProfileMatchers) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("bootprofilematchers").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *bootProfileMatchers) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("bootprofilematchers").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched bootProfileMatcher.
func (c *bootProfileMatchers) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.BootProfileMatcher, err error) {
	result = &v1alpha1.BootProfileMatcher{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("bootprofilematchers").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
