/*
Copyright (c) 2020 Mandelsoft. All rights reserved. This file is licensed under the Apache Software License, v. 2 except as noted otherwise in the LICENSE file

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

     http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"time"

	v1alpha1 "github.com/mandelsoft/kipxe/pkg/apis/ipxe/v1alpha1"
	scheme "github.com/mandelsoft/kipxe/pkg/client/ipxe/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// MatchersGetter has a method to return a MatcherInterface.
// A group's client should implement this interface.
type MatchersGetter interface {
	Matchers(namespace string) MatcherInterface
}

// MatcherInterface has methods to work with Matcher resources.
type MatcherInterface interface {
	Create(*v1alpha1.Matcher) (*v1alpha1.Matcher, error)
	Update(*v1alpha1.Matcher) (*v1alpha1.Matcher, error)
	UpdateStatus(*v1alpha1.Matcher) (*v1alpha1.Matcher, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.Matcher, error)
	List(opts v1.ListOptions) (*v1alpha1.MatcherList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.Matcher, err error)
	MatcherExpansion
}

// matchers implements MatcherInterface
type matchers struct {
	client rest.Interface
	ns     string
}

// newMatchers returns a Matchers
func newMatchers(c *IpxeV1alpha1Client, namespace string) *matchers {
	return &matchers{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the matcher, and returns the corresponding matcher object, and an error if there is any.
func (c *matchers) Get(name string, options v1.GetOptions) (result *v1alpha1.Matcher, err error) {
	result = &v1alpha1.Matcher{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("matchers").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of Matchers that match those selectors.
func (c *matchers) List(opts v1.ListOptions) (result *v1alpha1.MatcherList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.MatcherList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("matchers").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested matchers.
func (c *matchers) Watch(opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("matchers").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a matcher and creates it.  Returns the server's representation of the matcher, and an error, if there is any.
func (c *matchers) Create(matcher *v1alpha1.Matcher) (result *v1alpha1.Matcher, err error) {
	result = &v1alpha1.Matcher{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("matchers").
		Body(matcher).
		Do().
		Into(result)
	return
}

// Update takes the representation of a matcher and updates it. Returns the server's representation of the matcher, and an error, if there is any.
func (c *matchers) Update(matcher *v1alpha1.Matcher) (result *v1alpha1.Matcher, err error) {
	result = &v1alpha1.Matcher{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("matchers").
		Name(matcher.Name).
		Body(matcher).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *matchers) UpdateStatus(matcher *v1alpha1.Matcher) (result *v1alpha1.Matcher, err error) {
	result = &v1alpha1.Matcher{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("matchers").
		Name(matcher.Name).
		SubResource("status").
		Body(matcher).
		Do().
		Into(result)
	return
}

// Delete takes name of the matcher and deletes it. Returns an error if one occurs.
func (c *matchers) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("matchers").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *matchers) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("matchers").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched matcher.
func (c *matchers) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.Matcher, err error) {
	result = &v1alpha1.Matcher{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("matchers").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
