/*
Copyright (c) 2020 Mandelsoft. All rights reserved. This file is licensed under the Apache Software License, v. 2 except as noted otherwise in the LICENSE file

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

     http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"time"

	v1alpha1 "github.com/mandelsoft/kipxe/pkg/apis/ipxe/v1alpha1"
	scheme "github.com/mandelsoft/kipxe/pkg/client/ipxe/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// MetaDataMappersGetter has a method to return a MetaDataMapperInterface.
// A group's client should implement this interface.
type MetaDataMappersGetter interface {
	MetaDataMappers(namespace string) MetaDataMapperInterface
}

// MetaDataMapperInterface has methods to work with MetaDataMapper resources.
type MetaDataMapperInterface interface {
	Create(*v1alpha1.MetaDataMapper) (*v1alpha1.MetaDataMapper, error)
	Update(*v1alpha1.MetaDataMapper) (*v1alpha1.MetaDataMapper, error)
	UpdateStatus(*v1alpha1.MetaDataMapper) (*v1alpha1.MetaDataMapper, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.MetaDataMapper, error)
	List(opts v1.ListOptions) (*v1alpha1.MetaDataMapperList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.MetaDataMapper, err error)
	MetaDataMapperExpansion
}

// metaDataMappers implements MetaDataMapperInterface
type metaDataMappers struct {
	client rest.Interface
	ns     string
}

// newMetaDataMappers returns a MetaDataMappers
func newMetaDataMappers(c *IpxeV1alpha1Client, namespace string) *metaDataMappers {
	return &metaDataMappers{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the metaDataMapper, and returns the corresponding metaDataMapper object, and an error if there is any.
func (c *metaDataMappers) Get(name string, options v1.GetOptions) (result *v1alpha1.MetaDataMapper, err error) {
	result = &v1alpha1.MetaDataMapper{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("metadatamappers").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of MetaDataMappers that match those selectors.
func (c *metaDataMappers) List(opts v1.ListOptions) (result *v1alpha1.MetaDataMapperList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.MetaDataMapperList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("metadatamappers").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested metaDataMappers.
func (c *metaDataMappers) Watch(opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("metadatamappers").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a metaDataMapper and creates it.  Returns the server's representation of the metaDataMapper, and an error, if there is any.
func (c *metaDataMappers) Create(metaDataMapper *v1alpha1.MetaDataMapper) (result *v1alpha1.MetaDataMapper, err error) {
	result = &v1alpha1.MetaDataMapper{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("metadatamappers").
		Body(metaDataMapper).
		Do().
		Into(result)
	return
}

// Update takes the representation of a metaDataMapper and updates it. Returns the server's representation of the metaDataMapper, and an error, if there is any.
func (c *metaDataMappers) Update(metaDataMapper *v1alpha1.MetaDataMapper) (result *v1alpha1.MetaDataMapper, err error) {
	result = &v1alpha1.MetaDataMapper{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("metadatamappers").
		Name(metaDataMapper.Name).
		Body(metaDataMapper).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *metaDataMappers) UpdateStatus(metaDataMapper *v1alpha1.MetaDataMapper) (result *v1alpha1.MetaDataMapper, err error) {
	result = &v1alpha1.MetaDataMapper{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("metadatamappers").
		Name(metaDataMapper.Name).
		SubResource("status").
		Body(metaDataMapper).
		Do().
		Into(result)
	return
}

// Delete takes name of the metaDataMapper and deletes it. Returns an error if one occurs.
func (c *metaDataMappers) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("metadatamappers").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *metaDataMappers) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("metadatamappers").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched metaDataMapper.
func (c *metaDataMappers) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.MetaDataMapper, err error) {
	result = &v1alpha1.MetaDataMapper{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("metadatamappers").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
