apiVersion: ipxe.mandelsoft.org/v1alpha1
kind: BootProfile
metadata:
  name: default
  namespace: {{ .Release.Namespace }}
spec:
  resources:
    - path: cacert
      documentName: cacert
    - path: metadata
      documentName: info
