{{- if and .Values.partition .Values.senderips }}
apiVersion: ipxe.mandelsoft.org/v1alpha1
kind: MetaDataMapper
metadata:
  name: partition
  namespace: {{ .Release.Namespace }}
spec:
  weight: 110

  mapping:
    partitions:
{{- range $index, $ip := .Values.senderips }}
      {{ $ip }}: {{ $.Values.partition.id }}
{{- end }}
    metadata:
      <<<: (( merge ))
      partition: (( require(sum[reverse(__X-Forwarded-For__ [ ORIGIN ])|~|s,v|-> .partitions[v] || s]) || ~~ ))
{{- end }}
