apiVersion: ipxe.mandelsoft.org/v1alpha1
kind: BootResource
metadata:
  name: ipxe
  namespace: {{ .Release.Namespace }}
spec:
  mimeType: text/plain
  text: |+
    #!ipxe

    dhcp
    kernel: {{ "{{" }} .kernel }}
    initrd: {{ "{{" }} .initrd }}
    boot:   {{ "{{" }} .boot }}

