/*
Copyright (c) 2020 Mandelsoft. All rights reserved. This file is licensed under the Apache Software License, v. 2 except as noted otherwise in the LICENSE file

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

     http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/mandelsoft/kipxe/pkg/apis/ipxe/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeMetaDataMappers implements MetaDataMapperInterface
type FakeMetaDataMappers struct {
	Fake *FakeIpxeV1alpha1
	ns   string
}

var metadatamappersResource = schema.GroupVersionResource{Group: "ipxe.mandelsoft.org", Version: "v1alpha1", Resource: "metadatamappers"}

var metadatamappersKind = schema.GroupVersionKind{Group: "ipxe.mandelsoft.org", Version: "v1alpha1", Kind: "MetaDataMapper"}

// Get takes name of the metaDataMapper, and returns the corresponding metaDataMapper object, and an error if there is any.
func (c *FakeMetaDataMappers) Get(name string, options v1.GetOptions) (result *v1alpha1.MetaDataMapper, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(metadatamappersResource, c.ns, name), &v1alpha1.MetaDataMapper{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.MetaDataMapper), err
}

// List takes label and field selectors, and returns the list of MetaDataMappers that match those selectors.
func (c *FakeMetaDataMappers) List(opts v1.ListOptions) (result *v1alpha1.MetaDataMapperList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(metadatamappersResource, metadatamappersKind, c.ns, opts), &v1alpha1.MetaDataMapperList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.MetaDataMapperList{ListMeta: obj.(*v1alpha1.MetaDataMapperList).ListMeta}
	for _, item := range obj.(*v1alpha1.MetaDataMapperList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested metaDataMappers.
func (c *FakeMetaDataMappers) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(metadatamappersResource, c.ns, opts))

}

// Create takes the representation of a metaDataMapper and creates it.  Returns the server's representation of the metaDataMapper, and an error, if there is any.
func (c *FakeMetaDataMappers) Create(metaDataMapper *v1alpha1.MetaDataMapper) (result *v1alpha1.MetaDataMapper, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(metadatamappersResource, c.ns, metaDataMapper), &v1alpha1.MetaDataMapper{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.MetaDataMapper), err
}

// Update takes the representation of a metaDataMapper and updates it. Returns the server's representation of the metaDataMapper, and an error, if there is any.
func (c *FakeMetaDataMappers) Update(metaDataMapper *v1alpha1.MetaDataMapper) (result *v1alpha1.MetaDataMapper, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(metadatamappersResource, c.ns, metaDataMapper), &v1alpha1.MetaDataMapper{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.MetaDataMapper), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeMetaDataMappers) UpdateStatus(metaDataMapper *v1alpha1.MetaDataMapper) (*v1alpha1.MetaDataMapper, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(metadatamappersResource, "status", c.ns, metaDataMapper), &v1alpha1.MetaDataMapper{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.MetaDataMapper), err
}

// Delete takes name of the metaDataMapper and deletes it. Returns an error if one occurs.
func (c *FakeMetaDataMappers) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(metadatamappersResource, c.ns, name), &v1alpha1.MetaDataMapper{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeMetaDataMappers) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(metadatamappersResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.MetaDataMapperList{})
	return err
}

// Patch applies the patch and returns the patched metaDataMapper.
func (c *FakeMetaDataMappers) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.MetaDataMapper, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(metadatamappersResource, c.ns, name, pt, data, subresources...), &v1alpha1.MetaDataMapper{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.MetaDataMapper), err
}
