/*
Copyright (c) 2020 Mandelsoft. All rights reserved. This file is licensed under the Apache Software License, v. 2 except as noted otherwise in the LICENSE file

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

     http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/mandelsoft/kipxe/pkg/apis/ipxe/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeMatchers implements MatcherInterface
type FakeMatchers struct {
	Fake *FakeIpxeV1alpha1
	ns   string
}

var matchersResource = schema.GroupVersionResource{Group: "ipxe.mandelsoft.org", Version: "v1alpha1", Resource: "matchers"}

var matchersKind = schema.GroupVersionKind{Group: "ipxe.mandelsoft.org", Version: "v1alpha1", Kind: "BootProfileMatcher"}

// Get takes name of the matcher, and returns the corresponding matcher object, and an error if there is any.
func (c *FakeMatchers) Get(name string, options v1.GetOptions) (result *v1alpha1.BootProfileMatcher, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(matchersResource, c.ns, name), &v1alpha1.BootProfileMatcher{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.BootProfileMatcher), err
}

// List takes label and field selectors, and returns the list of Matchers that match those selectors.
func (c *FakeMatchers) List(opts v1.ListOptions) (result *v1alpha1.BootProfileMatcherList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(matchersResource, matchersKind, c.ns, opts), &v1alpha1.BootProfileMatcherList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.BootProfileMatcherList{ListMeta: obj.(*v1alpha1.BootProfileMatcherList).ListMeta}
	for _, item := range obj.(*v1alpha1.BootProfileMatcherList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested matchers.
func (c *FakeMatchers) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(matchersResource, c.ns, opts))

}

// Create takes the representation of a matcher and creates it.  Returns the server's representation of the matcher, and an error, if there is any.
func (c *FakeMatchers) Create(matcher *v1alpha1.BootProfileMatcher) (result *v1alpha1.BootProfileMatcher, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(matchersResource, c.ns, matcher), &v1alpha1.BootProfileMatcher{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.BootProfileMatcher), err
}

// Update takes the representation of a matcher and updates it. Returns the server's representation of the matcher, and an error, if there is any.
func (c *FakeMatchers) Update(matcher *v1alpha1.BootProfileMatcher) (result *v1alpha1.BootProfileMatcher, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(matchersResource, c.ns, matcher), &v1alpha1.BootProfileMatcher{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.BootProfileMatcher), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeMatchers) UpdateStatus(matcher *v1alpha1.BootProfileMatcher) (*v1alpha1.BootProfileMatcher, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(matchersResource, "status", c.ns, matcher), &v1alpha1.BootProfileMatcher{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.BootProfileMatcher), err
}

// Delete takes name of the matcher and deletes it. Returns an error if one occurs.
func (c *FakeMatchers) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(matchersResource, c.ns, name), &v1alpha1.BootProfileMatcher{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeMatchers) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(matchersResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.BootProfileMatcherList{})
	return err
}

// Patch applies the patch and returns the patched matcher.
func (c *FakeMatchers) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.BootProfileMatcher, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(matchersResource, c.ns, name, pt, data, subresources...), &v1alpha1.BootProfileMatcher{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.BootProfileMatcher), err
}
